name: Test

on:
  push:
    branches:
      - main

jobs:
#  docker:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cyata:latest
#          build-args: |
#            NEXT_PUBLIC_TURNSTILE_SITE_KEY=${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY }}

  deploy:
    runs-on: ubuntu-latest
#    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Refresh SST
        run: npx sst refresh
        env:
          NOMAD_URL: ${{ secrets.NOMAD_URL }}
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
          DOMAIN: ${{ secrets.DOMAIN }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}
          CYATA_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/cyata:latest
          CF_DNS_API_TOKEN: ${{ secrets.CF_DNS_API_TOKEN }}

      - name: Deploy SST
        run: npx sst deploy
        env:
          NOMAD_URL: ${{ secrets.NOMAD_URL }}
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
          DOMAIN: ${{ secrets.DOMAIN }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}
          CYATA_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/cyata:latest
          CF_DNS_API_TOKEN: ${{ secrets.CF_DNS_API_TOKEN }}